### ISSUE TITLE
Cannot start application

### ISSUE THREAD

**Issue by Grillpotat** [Issung/GChan#44]
Upon trying to install I get message cannot start application with error message
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Potat\Desktop\GChan5.3.0\GChan.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/Users/Potat/Desktop/GChan5.3.0/4chanIcon.ico.deploy did not succeed.
		+ Could not find file 'C:\Users\Potat\Desktop\GChan5.3.0\4chanIcon.ico.deploy'.
		+ Could not find file 'C:\Users\Potat\Desktop\GChan5.3.0\4chanIcon.ico.deploy'.
		+ Could not find file 'C:\Users\Potat\Desktop\GChan5.3.0\4chanIcon.ico.deploy'.
		
		ERROR DETAILS
	Following errors were detected during this operation.
	* [07/06/2024 20.15.46] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/Users/Potat/Desktop/GChan5.3.0/4chanIcon.ico.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\Users\Potat\Desktop\GChan5.3.0\4chanIcon.ico.deploy'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\Users\Potat\Desktop\GChan5.3.0\4chanIcon.ico.deploy'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- Could not find file 'C:\Users\Potat\Desktop\GChan5.3.0\4chanIcon.ico.deploy'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

**Comment by Issung** [comment]
Hi there, I've never seen such an issue before, and thank you for uploading the logs, they are a bit bizzare, as none of the stacktrace appears to be my code. 
I'm confused as to when this error is occuring, you say "Upon trying to install" but GChan does not have an installer, I only share a zip file with the application contents. Did you get the app from here on GitHub?

**Comment by Grillpotat** [comment]
> Hi there, I've never seen such an issue before, and thank you for uploading the logs, they are a bit bizzare, as none of the stacktrace appears to be my code. I'm confused as to when this error is occuring, you say "Upon trying to install" but GChan does not have an installer, I only share a zip file with the application contents. Did you get the app from here on GitHub?

yes the "installer" is the GChan.application but the GChan.exe works normally though

**Comment by Grillpotat** [comment]
> Hi there, I've never seen such an issue before, and thank you for uploading the logs, they are a bit bizzare, as none of the stacktrace appears to be my code. I'm confused as to when this error is occuring, you say "Upon trying to install" but GChan does not have an installer, I only share a zip file with the application contents. Did you get the app from here on GitHub?

Yes the "installer" is the GChan.appication but the Gchan.exe work normally

**Comment by Issung** [comment]
Ah, I've never tried/tested using that file, not the way I intended people to use GChan. I'll see if I can reproduce it on my machine and figure out why it's not happy.
